version: "3.0"
services:
  database: 
    image: prumme/custom-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: prumme/custom-adminer
    ports:
      - "8080:8080"  
    depends_on:
      - database

  composer:
    image: prumme/custom-composer

  symfony:
    image: prumme/custom-symfo
    ports:
      - "8000:8000"
    depends_on:
      - database
      - composer