version: "3.0"
services:
  database: 
    image: custom-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: custom-adminer
    ports:
      - "8080:8080"  
    depends_on:
      - database

  composer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app

  # symfony:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - database
  #     - composer
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@database:5432/postgres