version: "3.0"
services:
  database: 
    image: custom-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: custom-adminer
    ports:
      - "8080:8080"  
    depends_on:
      - database